title: Standalone Action BL For Logged-In Users
level: Beginner
targets:
  - jvm
tags:
  - business logic
  - action
  - standalone
  - authorize
  - logged in
links:
  - /doc/guides/backend/BusinessLogic.md
  - /doc/guides/backend/Authorizer.md
  - /doc/guides/common/Data.md
