title : Standalone Query BL With Public Access
level: Beginner
tags:
  - business logic
  - query
  - standalone
  - authorize
  - public
links:
  - /doc/guides/backend/BusinessLogic.md
  - /doc/guides/backend/Authorizer.md
  - /doc/guides/common/Data.md
