title: Communication Basics
level: Beginner
targets:
  - common
tags:
  - communication
  - comm
  - business object
  - entity
  - action
  - query
  - create
  - read
  - update
  - delete
  - all
  - execute
